# Local server settings
host: 0.0.0.0 # Ignored by Github Pages

# Build settings
url: "https://www.dominicsayers.com" # the base hostname & protocol for your site
permalink: :title/

plugins:
  - jemoji
  - jekyll-sitemap

collections:
  tag_pages:
    output: true
    permalink: /tag/:name/
  authors:
    output: true
    permalink: /author/:name/

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      author: Dominic Sayers
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page

# Site settings
title: "Dominic Sayers"
description: "English as tuppence, changing yet changeless as canal water, nestling in green nowhere, opsimath and eremite"
logo: "/assets/images/home.png"
cover: "/assets/images/bg_landing_page.jpg"

name: 'Dominic Sayers'
author: 'Dominic Sayers'
author_image: "/assets/images/dominicsayers.jpg"
author_thumb: "/assets/images/Dominic_2016_256px.jpg"

# social icons and sharing options
social:
  linkedin:
    name: LinkedIn
    url:  https://uk.linkedin.com/in/dominicsayers
    desc: Connect with me on LinkedIn
    contactable: true
  twitter:
    name: Twitter
    handle: dominicsayers
    url:  https://twitter.com/dominicsayers
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: '?text='
    share_link: "&amp;url="
    contactable: true
  github:
    url:  https://github.com/dominicsayers
    desc: Fork me on github
  stack-overflow:
    url:  http://stackoverflow.com/users/63349/dominic-sayers
    desc: Follow me on StackOverflow
  quora:
    url:  https://www.quora.com/profile/Dominic-Sayers
    desc: Follow me on Quora
  angellist:
    url:  https://angel.co/dominicsayers
    desc: Follow me on AngelList
  # medium:
  #   url: https://medium.com/@dominic.sayers
  #   desc: Follow me on Medium
  wikipedia-w:
    url: https://en.wikipedia.org/wiki/User:Dominic_Sayers
    desc: My contributions to Wikipedia
  flickr:
    url: https://www.flickr.com/photos/dominicsayers/
    desc: My photos on Flickr
  skype:
    name: Skype
    handle: dominicsayers
    url: skype:dominicsayers?call
    desc: Chat to me on Skype
    contactable: true
  envelope:
    name: Email
    url: mailto:dominic@sayers.cc
    desc: Email me if all else fails
    contactable: true
  disqus:
    handle: dominicsayers

# Developer portfolio
portfolio:
  -
    name: OpenCorporates
    url: https://opencorporates.com
    thumbnail: oc.png
    technology:
      - Ruby on Rails
      - MySQL
      - Elasticsearch
      - Redis
      - Resque
      - TDD
      - Continuous integration
      - Agile
  -
    name: Xenapto
    url: https://xenapto.com
    thumbnail: xenapto.png
    technology:
      - Ruby on Rails
      - PostgreSQL
      - Elasticsearch
      - Javascript
      - Bootstrap
      - Redis
      - Resque
      - TDD
      - Continuous integration
      - Agile
  -
    name: Anthemis Group
    url: https://anthemis.com
    thumbnail: anthemis.png
    technology:
      - Ruby on Rails
      - Slack
      - Podio
      - Neo4J
      - Email (inbound + outbound)
      - Evernote
  -
    name: Dominic Sayers
    url: https://www.dominicsayers.com
    thumbnail: dominicsayers.png
    technology:
      - Jekyll
      - Liquid
      - Front matter
      - Github Pages
  -
    name: Cricket data
    url: http://cricdata.org
    thumbnail: cricdata.png
    technology:
      - Ruby on Rails
      - MongoDB
  -
    name: is_email
    url: http://isemail.info
    thumbnail: isemail.png
    technology:
      - Email
      - Open source
      - RFCs
      - Standards
      - PHP
