# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Dominic Sayers"
description: > # this means to ignore newlines until "email:"
   CTO

email: dominic@sayers.cc
#blog logo
logo: "/assets/images/home.png"
# blog cover
cover: "/assets/images/bg_landing_page.jpg"

name: 'Dominic Sayers'
author: 'Dominic Sayers'
author_image: "/assets/images/dominicsayers.jpg"

paginate:	5
permalink: none

url: "http://new.dominicsayers.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dominicsayers'

#fill in disqus shortname to use disqus
disqus: dominicsayers

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dominicsayers
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: '?text='
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dominicsayers
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
