# Local server settings
host: 0.0.0.0 # Ignored by Github Pages

# Build settings
url: "https://blog.dominicsayers.com" # the base hostname & protocol for your site
permalink: :title/

gems:
  - jemoji
  - jekyll-sitemap

collections:
  tag_pages:
    output: true
    permalink: /tag/:name/

# Site settings
title: "Dominic Sayers"
description: "English as tuppence, changing yet changeless as canal water, nestling in green nowhere, opsimath and eremite"
email: dominic@sayers.cc
logo: "/assets/images/home.png"
cover: "/assets/images/bg_landing_page.jpg"

name: 'Dominic Sayers'
author: 'Dominic Sayers'
author_image: "/assets/images/dominicsayers.jpg"

twitter_handle: '@dominicsayers'
disqus: dominicsayers

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dominicsayers
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: '?text='
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dominicsayers
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
